/programs/anaconda/2019.07/lib/python3.7/site-packages/dask_jobqueue/config.py:12: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
/programs/anaconda/2019.07/lib/python3.7/site-packages/distributed/deploy/local.py:118: UserWarning: diagnostics_port has been deprecated. Please use `dashboard_address=` instead
  "diagnostics_port has been deprecated. "
/programs/anaconda/2019.07/lib/python3.7/site-packages/distributed/worker.py:3177: UserWarning: Large object of size 5.75 MB detected in task graph: 
  [<xarray.Dataset>
Dimensions:  (time: 89833)
Coord ... 9 226.1, 1, 22]
Consider scattering large objects ahead of time
with client.scatter to reduce scheduler burden and 
keep data on workers

    future = client.submit(func, big_data)    # bad

    big_future = client.scatter(big_data)     # good
    future = client.submit(func, big_future)  # good
  % (format_bytes(len(b)), s)
Traceback (most recent call last):
  File "/data/scratch/richteny/thesis/cosipy_test_space/run_spotpy_full.py", line 13, in <module>
    best_summary = psample(obs=obs,count=count, rep=1000)
  File "/data/scratch/richteny/thesis/cosipy_test_space/spotpy_full.py", line 110, in psample
    sampler.sample(rep)
  File "/programs/anaconda/2019.07/lib/python3.7/site-packages/spotpy/algorithms/mcmc.py", line 122, in sample
    for curChain,randompar,simulations in self.repeat(param_generator):
  File "/programs/anaconda/2019.07/lib/python3.7/site-packages/spotpy/parallel/sequential.py", line 27, in __call__
    data = self.process(job)
  File "/programs/anaconda/2019.07/lib/python3.7/site-packages/spotpy/algorithms/_algorithm.py", line 467, in simulate
    model_result = self.setup.simulation(self.partype(*all_params))
  File "/data/scratch/richteny/thesis/cosipy_test_space/spotpy_full.py", line 69, in simulation
    albedo_aging = x.albedo_aging, albedo_depth = x.albedo_depth, count=self.count)
  File "/data/scratch/richteny/thesis/cosipy_test_space/COSIPY.py", line 122, in main
    run_cosipy(cluster, IO, DATA, RESULT, RESTART, futures, opt_dict=opt_dict)
  File "/data/scratch/richteny/thesis/cosipy_test_space/COSIPY.py", line 377, in run_cosipy
    LAYER_IRREDUCIBLE_WATER,LAYER_REFREEZE,stake_names,stat,df_eval = future.result()
  File "/programs/anaconda/2019.07/lib/python3.7/site-packages/distributed/client.py", line 221, in result
    six.reraise(*result)
  File "/programs/anaconda/2019.07/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/data/scratch/richteny/thesis/cosipy_test_space/cosipy/cpkernel/cosipy_core.py", line 261, in cosipy_core
    sw_radiation_net, U2[t], RAIN, SLOPE, LWin=LWin[t], opt_dict=opt_dict)
ValueError: not enough values to unpack (expected 16, got 15)
