2025-04-22 10:43:12.723456: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-22 10:43:12.726985: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-22 10:43:12.737355: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1745311392.754620   47270 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1745311392.759855   47270 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1745311392.773779   47270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1745311392.773795   47270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1745311392.773797   47270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1745311392.773799   47270 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-04-22 10:43:12.778022: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2025-04-22 10:43:16.673550: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/data.py:433: UserWarning: The `mutable` kwarg was not specified. Before v4.1.0 it defaulted to `pm.Data(mutable=True)`, which is equivalent to using `pm.MutableData()`. In v4.1.0 the default changed to `pm.Data(mutable=False)`, equivalent to `pm.ConstantData`. Use `pm.ConstantData`/`pm.MutableData` or pass `pm.Data(..., mutable=False/True)` to avoid this warning.
  warnings.warn(
Only 10 samples in chain.
Multiprocess sampling (4 chains in 4 jobs)
DEMetropolisZ: [rrrfactor, albsnow, albice, albfirn, albaging, albdepth, iceroughness]
2025-04-22 10:44:07.250550: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1745311447.268273   47756 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1745311447.273626   47756 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1745311447.287628   47756 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1745311447.287644   47756 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1745311447.287646   47756 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1745311447.287648   47756 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-04-22 10:44:10.989508: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/data.py:433: UserWarning: The `mutable` kwarg was not specified. Before v4.1.0 it defaulted to `pm.Data(mutable=True)`, which is equivalent to using `pm.MutableData()`. In v4.1.0 the default changed to `pm.Data(mutable=False)`, equivalent to `pm.ConstantData`. Use `pm.ConstantData`/`pm.MutableData` or pass `pm.Data(..., mutable=False/True)` to avoid this warning.
  warnings.warn(
Only 10 samples in chain.
Multiprocess sampling (4 chains in 4 jobs)
DEMetropolisZ: [rrrfactor, albsnow, albice, albfirn, albaging, albdepth, iceroughness]
Traceback (most recent call last):
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/forkserver.py", line 274, in main
    code = _serve_one(child_r, fds,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/forkserver.py", line 313, in _serve_one
    code = spawn._main(child_r, parent_sentinel)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/data/scratch/richteny/thesis/cosipy_test_space/emulator_easy_mcmc.py", line 278, in <module>
    post = pm.sample(draws=10, tune=1, step=step, initvals=initvals, return_inferencedata=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/mcmc.py", line 802, in sample
    _mp_sample(**sample_args, **parallel_args)
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/mcmc.py", line 1177, in _mp_sample
    sampler = ps.ParallelSampler(
              ^^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/parallel.py", line 402, in __init__
    self._samplers = [
                     ^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/parallel.py", line 403, in <listcomp>
    ProcessAdapter(
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/parallel.py", line 259, in __init__
    self._process.start()
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/context.py", line 300, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/popen_forkserver.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html
        
Traceback (most recent call last):
  File "/data/scratch/richteny/thesis/cosipy_test_space/emulator_easy_mcmc.py", line 278, in <module>
    post = pm.sample(draws=10, tune=1, step=step, initvals=initvals, return_inferencedata=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/mcmc.py", line 802, in sample
    _mp_sample(**sample_args, **parallel_args)
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/mcmc.py", line 1177, in _mp_sample
    sampler = ps.ParallelSampler(
              ^^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/parallel.py", line 402, in __init__
    self._samplers = [
                     ^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/parallel.py", line 403, in <listcomp>
    ProcessAdapter(
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/site-packages/pymc/sampling/parallel.py", line 259, in __init__
    self._process.start()
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/context.py", line 300, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/data/scratch/richteny/miniconda3/envs/pymc_env/lib/python3.11/multiprocessing/popen_forkserver.py", line 58, in _launch
    f.write(buf.getbuffer())
BrokenPipeError: [Errno 32] Broken pipe
